version: '3.4'

services:
  production_web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./docker/env/production/.env
    ports:
      - "80:80"
    volumes:
      - ./log/nginx/production:/opt/nginx/logs
      - ./log:/app/log
      - ./config/master.key:/app/config/master.key
      - ./docker/nginx/production/nginx.conf:/opt/nginx/conf/nginx.conf
    stdin_open: true
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        touch /app/log/production.log && touch /app/log/.keep
        chmod o+w /app/log/production.log
        crond
        /opt/nginx/sbin/nginx -g 'daemon off;'
