json.cost_price currency_format list.item.cost_price
json.selling_price currency_format list.item.selling_price
json.alive_barcodes_count unit_format list.item.alive_barcodes_count
json.unit_count unit_format list.unit_count
json.available_quantity unit_format list.available_quantity
